#!/bin/bash
if [[ $1 == "-" ]]; then

  file=$TEMP/Edit_$PPID$RANDOM
  cat > $file
  echo $file
  "$MYEDITOR" "$file" &
  (sleep 25; rm $file) &

else

  for file in "$@"
  do
    if [[ $file != -* && ! -e "$file" ]]; then
      echo -n "$file does not exist; create it? "
      read answer
      if [[ $answer == y* || $answer == Y* ]]; then
        touch "$file"
      else
        echo "Then I give up"
        exit 1
      fi
    fi
  done

  if [[ "$@" != "" ]]; then
    echo "Editing... $@"
    "$MYEDITOR" "$@"
  fi

fi