#!/bin/bash
if [[ $1 == "-" ]]; then
  if [[ ! $TEMP ]]; then
    echo "No TEMP env variable exists. "
    echo "TEMP names our global temporary directory, and it can be whatever you want."
    exit 1
  fi
  file=$TEMP/Editing_$PPID$RANDOM
  cat > $file
  echo $file
  "$MYEDITOR" "$file" &
  (sleep 25; rm $file) &

else

  for file in "$@"
  do
    if [[ $file != -* && ! -e "$file" ]]; then
      echo -n "$file does not exist; create it? "
      read answer
      if [[ $answer == y* || $answer == Y* ]]; then
        touch "$file"
      else
        echo "Then I give up"
        exit 1
      fi
    fi
  done

  if [[ "$@" != "" ]]; then
    echo "Editing... $@"
    "$MYEDITOR" "$@" &
  fi

fi