#!/bin/bash
if [[ $1 == -help ]]; then
  echo 'Usage: <cmd> | GroupBy [-having <expr> [-nocount] [-chars] ]'
  echo '  <expr> can be something like ">= 2", "<5", "==3"   '
  echo "  -nocount Don't display count "
  echo '  -chars Count characters instead of lines '
  echo 'Note: Alternatively, use "uniq -c", although that does not have -having '
  exit
fi


having=' > 0 '
nocount=""
dototal="0"
dochars=0

while [[ $1 != "" ]]; do
  if [[ $1 == -having ]]; then
    shift
    having=$1
    shift
  elif [[ $1 == -nocount ]]; then
    shift
    nocount=on
  elif [[ $1 == -total ]]; then
    shift
    dototal="1"
  elif [[ $1 == -c* || $1 == -chars ]]; then
    shift
    dochars=1
  fi
done


sort | \
  gawk -v "nocount=$nocount" -v "dototal=$dototal" -v "dochars=$dochars" '

    function punt(count, line){
      if (nocount!="on")
        printf count"\t->"
      print line;
    }

    BEGIN {
      x=-1; total=0; lastline=""; lastlen=0;
    }

    {
      total=total+lastlen;
      if (lastline != $0)  {
        if (x '"$having"' )
          punt(x, lastline)
        lastline=$0;
        lastlen=dochars ?length(lastline) :1;
        x=lastlen;
      }
      else {
        x=x+lastlen;
      }
    }

    END {
      if (x '"$having"' )
        punt(x, lastline)
      if (dototal) {
        print("--------")
        print(total "\t->Total")
      }
    }
  '
