#!/bin/bash
if [[ $1 == "-help" ]]; then
  echo "Usage: Unroll [-sep expr]"
  exit
fi

if [[ $1 == -sep* ]]; then
  shift;
  separator="-F$1"
  shift
elif [[ $1 == -F  ]]; then
  shift
  separator="-F$@"
elif [[ $1 == -F*  ]]; then
  separator="$@"
elif [[ $1 ]]; then
  separator="-F$@"
fi


if [[ $separator ]]; then
  gawk $separator '{for (i=1; i<=NF; i++) print $i;}'
else
  gawk '{for (i=1; i<=NF; i++) print $i;}'
fi
