#!/bin/bash
if [[ $KLONK_HOME != "" ]]; then
  mkdir -p "${KLONK_HOME}"
  klonkhome="$(cygpath -w $KLONK_HOME)"
  winpath "$@" | xargs klonk -home "$klonkhome" &
else
  winpath "$@" | xargs klonk &
fi
